server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: DEBUG
      org.springframework.web: WARN
      com.gfi.microservicios: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
  routes:
    microservicio-base: /servicio/**
    microservicio-dummy: /dummy/**
  sensitiveHeaders: Cookie, Set-Cookie
    
    
 #Distributed tracing
spring:
   zipkin:
      baseUrl: http://localhost:9411
